Data Science HW-6
================
Kasturi Bhamidipati
2022-12-02

# Problem 1

# Problem 2

## Importing and tidying data

We want to import the `homicides` dataset and make the necessary changes
as noted in the problem.

``` r
homicides = 
  read_csv("./data/homicide-data.csv") %>%
  janitor::clean_names()%>%
   mutate(
    city_state = str_c(city,state, sep = ","),
    victim_age = as.numeric(victim_age), 
    solved = as.numeric(disposition == "Closed by arrest"))%>%
  filter(
    !city_state %in% c("Dallas,TX", "Phoenix,AZ", "Kansas City,MO", "Tulsa,AL"),
    victim_race %in% c("Black", "White")
    ) %>% 
  select(victim_race, victim_age, victim_sex, city_state, solved)
```

## Baltimore `glm`

For the city of Baltimore, MD, we want to use the `glm` function to fit
a logistic regression with resolved vs unresolved as the outcome and
victim age, sex and race as predictors.

``` r
baltimore_glm = 
  homicides %>% 
  filter(city_state == "Baltimore,MD") %>% 
  glm(solved ~ victim_age + victim_sex + victim_race, 
      family = binomial(), 
      data = .) %>% 
  broom::tidy() %>% 
  janitor::clean_names()%>% 
  mutate(OR = exp(estimate),
         CI_lower = exp(estimate - 1.96*std_error),
         CI_upper = exp(estimate + 1.96*std_error))

baltimore_glm
```

    ## # A tibble: 4 × 8
    ##   term             estimate std_error statistic  p_value    OR CI_lower CI_upper
    ##   <chr>               <dbl>     <dbl>     <dbl>    <dbl> <dbl>    <dbl>    <dbl>
    ## 1 (Intercept)       0.310     0.171        1.81 7.04e- 2 1.36     0.975    1.91 
    ## 2 victim_age       -0.00673   0.00332     -2.02 4.30e- 2 0.993    0.987    1.00 
    ## 3 victim_sexMale   -0.854     0.138       -6.18 6.26e-10 0.426    0.325    0.558
    ## 4 victim_raceWhite  0.842     0.175        4.82 1.45e- 6 2.32     1.65     3.27

### Men Vs. Women Adjusted OR and 95% CI

Now we want to obtain the estimate and confidence interval of the
adjusted odds ratio for solving homicides comparing male victims to
female victims keeping all other variables fixed.

``` r
baltimore_glm %>%
  filter(term == "victim_sexMale") %>%
  select(OR, CI_lower, CI_upper) %>% 
  knitr::kable(digits = 3, col.names = c('Odds Ratio', 'Lower CI', 'Upper CI'))
```

| Odds Ratio | Lower CI | Upper CI |
|-----------:|---------:|---------:|
|      0.426 |    0.325 |    0.558 |

Therefore, we see that the adjusted odds ratio and its 95% CI for
solving homicides comparing male victims to female victims, keeping all
else constant is OR (95% CI) = 0.426 (0.325, 0.558).

## All cities `glm`

Now we want to do the same for all cities in the dataset.

``` r
homicides_glm = 
  homicides %>%
  nest(all_cities = -city_state) %>%
  mutate(all_glm = map(.x = all_cities, ~glm(solved ~ victim_age + victim_sex + victim_race,
         family = binomial(), data = .)),
         results = map(all_glm, broom::tidy))%>%
  select(-all_glm, -all_cities) %>% 
  unnest(cols = results) %>% 
  mutate(OR = exp(estimate),
         CI_lower = exp(estimate - 1.96 * std.error),
         CI_upper = exp(estimate + 1.96 * std.error)) %>% 
  filter(term == "victim_sexMale") %>% 
  select(city_state, OR, CI_lower, CI_upper)
  
homicides_table= 
  homicides_glm%>%
  knitr::kable(digits = 3, col.names = c('City, State','Odds Ratio', 'Lower CI', 'Upper CI'))

homicides_table
```

| City, State       | Odds Ratio | Lower CI | Upper CI |
|:------------------|-----------:|---------:|---------:|
| Albuquerque,NM    |      1.767 |    0.831 |    3.761 |
| Atlanta,GA        |      1.000 |    0.684 |    1.463 |
| Baltimore,MD      |      0.426 |    0.325 |    0.558 |
| Baton Rouge,LA    |      0.381 |    0.209 |    0.695 |
| Birmingham,AL     |      0.870 |    0.574 |    1.318 |
| Boston,MA         |      0.674 |    0.356 |    1.276 |
| Buffalo,NY        |      0.521 |    0.290 |    0.935 |
| Charlotte,NC      |      0.884 |    0.557 |    1.403 |
| Chicago,IL        |      0.410 |    0.336 |    0.501 |
| Cincinnati,OH     |      0.400 |    0.236 |    0.677 |
| Columbus,OH       |      0.532 |    0.378 |    0.750 |
| Denver,CO         |      0.479 |    0.236 |    0.971 |
| Detroit,MI        |      0.582 |    0.462 |    0.734 |
| Durham,NC         |      0.812 |    0.392 |    1.683 |
| Fort Worth,TX     |      0.669 |    0.397 |    1.127 |
| Fresno,CA         |      1.335 |    0.580 |    3.071 |
| Houston,TX        |      0.711 |    0.558 |    0.907 |
| Indianapolis,IN   |      0.919 |    0.679 |    1.242 |
| Jacksonville,FL   |      0.720 |    0.537 |    0.966 |
| Las Vegas,NV      |      0.837 |    0.608 |    1.154 |
| Long Beach,CA     |      0.410 |    0.156 |    1.082 |
| Los Angeles,CA    |      0.662 |    0.458 |    0.956 |
| Louisville,KY     |      0.491 |    0.305 |    0.790 |
| Memphis,TN        |      0.723 |    0.529 |    0.988 |
| Miami,FL          |      0.515 |    0.304 |    0.872 |
| Milwaukee,wI      |      0.727 |    0.499 |    1.060 |
| Minneapolis,MN    |      0.947 |    0.478 |    1.875 |
| Nashville,TN      |      1.034 |    0.685 |    1.562 |
| New Orleans,LA    |      0.585 |    0.422 |    0.811 |
| New York,NY       |      0.262 |    0.138 |    0.499 |
| Oakland,CA        |      0.563 |    0.365 |    0.868 |
| Oklahoma City,OK  |      0.974 |    0.624 |    1.520 |
| Omaha,NE          |      0.382 |    0.203 |    0.721 |
| Philadelphia,PA   |      0.496 |    0.378 |    0.652 |
| Pittsburgh,PA     |      0.431 |    0.265 |    0.700 |
| Richmond,VA       |      1.006 |    0.498 |    2.033 |
| San Antonio,TX    |      0.705 |    0.398 |    1.249 |
| Sacramento,CA     |      0.669 |    0.335 |    1.337 |
| Savannah,GA       |      0.867 |    0.422 |    1.780 |
| San Bernardino,CA |      0.500 |    0.171 |    1.462 |
| San Diego,CA      |      0.413 |    0.200 |    0.855 |
| San Francisco,CA  |      0.608 |    0.317 |    1.165 |
| St. Louis,MO      |      0.703 |    0.530 |    0.932 |
| Stockton,CA       |      1.352 |    0.621 |    2.942 |
| Tampa,FL          |      0.808 |    0.348 |    1.876 |
| Tulsa,OK          |      0.976 |    0.614 |    1.552 |
| Washington,DC     |      0.690 |    0.468 |    1.017 |

## Plot for Adjusted OR and 95% CI

Now we want to create a plot that shows the estimated ORs and CIs for
each city. We will also organize cities according to estimated OR.

``` r
homicides_or_plot= 
  homicides_glm %>%
  mutate( city_state = fct_reorder(city_state, OR)) %>%
  ggplot(aes(x = city_state, y =OR))+
  geom_point(alpha = 0.5)+
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper),
                alpha = 0.5)+ 
  labs(title = "Estimated Odds Ratios and their 95% CIs of Solved Homicides for Each City 
       (Comparing Male Vs. Female Victims)", 
       x = "City, State", 
       y = "Estimated ORs and 95% CIs")+
  theme(plot.title = element_text(size = 12, hjust = 0.5),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

homicides_or_plot
```

<img src="p8105_hw6_kb3246_files/figure-gfm/OR plot-1.png" width="90%" />

### About the Plot

-   From the plot above, it is evident that New York, NY has the lowest
    adjusted odds ratio for solving homicides, comparing male victims to
    female victims, keeping all else constant. On the other hand, we see
    that Albuquerque, NM has the highest OR for the same.

-   Next, for most cities, we can observe that the OR \<1, indicating
    that homicide cases with male victims have lower odds of being
    solved compared to homicide cases of female victims, keeping all
    else constant.

-   However, for Nashville, TN, Fresno, CA, Stockton, CA and
    Albuquerque, NM, we see that the OR \>1, indicating that homicide
    cases with male victims have higher odds of being solved compared to
    homicide cases of female victims, keeping all else constant.

-   It also appears to me that Atlanta, GA and Richmond, VA have OR \~1,
    indicating that homicide cases with male victims have similar odds
    of being solved compared to homicide cases of female victims,
    keeping all else constant.

-   I also notice that for some cities, the 95% CIs are very wide (for
    example - Albuquerque, NM and Stockton, CA).

# Problem 3

## Importing and cleaning `birthweight.csv`

``` r
birthweight = 
  read_csv("./data/birthweight.csv")%>% 
  janitor::clean_names()%>%
  mutate(babysex = as.factor(babysex),
         frace = as.factor(frace),
         malform = as.factor(malform),
         mrace = as.factor(mrace))

sum(is.na(birthweight))
```

    ## [1] 0

Therefore, we cleaned the data as appropriate; converted numeric to
factor where appropriate and checked for missing data using
`sum(is.na())`. No missing data were found in the `birthweight.csv`
dataset.

## Model 1 - Proposed model

Studies have shown that the baby’s sex, mother’s age at delivery, race,
income and parity are possible factors that affect the weight of an
infant at birth.

Therefore, for `model1` I included the variables `babysex`, `fincome`,
`momage`, `mrace` and `parity` as possible predictors of birthweight.
This model is based on a hypothesized structure for the factors that
underly birthweight.

``` r
model1 = lm(bwt ~ babysex+ fincome + momage + mrace + parity, data = birthweight)

model1
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ babysex + fincome + momage + mrace + parity, 
    ##     data = birthweight)
    ## 
    ## Coefficients:
    ## (Intercept)     babysex2      fincome       momage       mrace2       mrace3  
    ##    3187.115      -79.367        0.692        3.676     -289.853     -141.161  
    ##      mrace4       parity  
    ##    -185.366      -21.622

### `model1` Residual Plot

``` r
model1_plot =
  birthweight %>%
  modelr::add_predictions(model1) %>%
  modelr::add_residuals(model1) %>%
  ggplot(aes(x = pred, y = resid))+
  geom_violin()+
  labs(title = "Model 1 Residuals Plot",
       x = "Predicted",
       y = "Residuals")

model1_plot
```

<img src="p8105_hw6_kb3246_files/figure-gfm/model1 plot-1.png" width="90%" />

## Model 2

`model2` uses length at birth and gestational age as predictors (main
effects only).

``` r
model2 = lm(bwt ~ blength + gaweeks, data = birthweight)

model2
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ blength + gaweeks, data = birthweight)
    ## 
    ## Coefficients:
    ## (Intercept)      blength      gaweeks  
    ##    -4347.67       128.56        27.05

## Model 3

``` r
model3 = lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = birthweight)

model3
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ bhead + blength + babysex + bhead * blength + 
    ##     bhead * babysex + blength * babysex + bhead * blength * babysex, 
    ##     data = birthweight)
    ## 
    ## Coefficients:
    ##            (Intercept)                   bhead                 blength  
    ##             -7176.8170                181.7956                102.1269  
    ##               babysex2           bhead:blength          bhead:babysex2  
    ##              6374.8684                 -0.5536               -198.3932  
    ##       blength:babysex2  bhead:blength:babysex2  
    ##              -123.7729                  3.8781

## Crossvalidation

Now we want to compare `model1` with `model2` and `model3` in terms of
the cross-validated prediction error by using `crossv_mc` and functions
in `purrr` as appropriate.

``` r
birthweight_cv = crossv_mc(birthweight, 100) %>% 
  mutate(train = map(train, as_tibble),
         test = map(test, as_tibble)) %>% 
  mutate(model1_cv = map(train, ~lm(bwt ~ wtgain, data = .x)),
         model2_cv = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
         model3_cv = map(train, ~lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = .x))) %>% 
  mutate(rmse_model1 = map2_dbl(model1_cv, test, ~rmse(model = .x, data = .y)),
         rmse_model2 = map2_dbl(model2_cv, test, ~rmse(model = .x, data = .y)), 
         rmse_model3 = map2_dbl(model3_cv, test, ~rmse(model = .x, data = .y)))
```

### Crossvalidation Residual Plot

``` r
cv_plot= 
  birthweight_cv %>%
  select(starts_with("rmse")) %>% 
  pivot_longer(everything(), 
               names_to = "model",
               values_to = "rmse",
               names_prefix = "rmse_") %>% 
  ggplot(aes(x = model, y = rmse)) + 
  geom_violin()+
  labs(title = "Comparing the Birthweight Models",
      x = "Model",
      y = "rmse")+
  theme(plot.title = element_text(size = 12, hjust = 0.5))
  

cv_plot
```

<img src="p8105_hw6_kb3246_files/figure-gfm/cv plot-1.png" width="90%" />

#### Inference About the Models

Here, it is evident that `model3` has the lowest RMSE, and therefore,
would be the best model among the three.
